"""Shared Mathews configuration contracts."""

from mathews_configuration.repository import (
    MANDATORY_PROHIBITED_OPERATIONS,
    MANDATORY_PROHIBITED_PATHS,
    REQUIRED_PREFLIGHT_CHECKS,
    SIMULATOR_DESTINATION_PLACEHOLDER,
    ArtifactSettings,
    AssertionCatalogEntry,
    AssertionKind,
    E2EFlow,
    GitIdentity,
    GitSettings,
    OperationKind,
    PreflightCheck,
    PreflightCheckCode,
    PreflightStatus,
    ProhibitedOperation,
    RepositoryConfiguration,
    RepositoryConfigurationError,
    RepositoryPreflightReport,
    RepositorySettings,
    SimulatorSettings,
    TestOperation,
    XcodeContainerKind,
    XcodeSettings,
)
from mathews_configuration.secrets import (
    SecretProvider,
    SecretReference,
    SecretReferenceError,
    SecretValue,
    SecretValueError,
    redact_text,
)

__all__ = [
    "MANDATORY_PROHIBITED_OPERATIONS",
    "MANDATORY_PROHIBITED_PATHS",
    "REQUIRED_PREFLIGHT_CHECKS",
    "SIMULATOR_DESTINATION_PLACEHOLDER",
    "ArtifactSettings",
    "AssertionCatalogEntry",
    "AssertionKind",
    "E2EFlow",
    "GitIdentity",
    "GitSettings",
    "OperationKind",
    "PreflightCheck",
    "PreflightCheckCode",
    "PreflightStatus",
    "ProhibitedOperation",
    "RepositoryConfiguration",
    "RepositoryConfigurationError",
    "RepositoryPreflightReport",
    "RepositorySettings",
    "SecretProvider",
    "SecretReference",
    "SecretReferenceError",
    "SecretValue",
    "SecretValueError",
    "SimulatorSettings",
    "TestOperation",
    "XcodeContainerKind",
    "XcodeSettings",
    "redact_text",
]
