"use client";

import { useState } from "react";
import { DocNav } from "../components/doc-nav";

type RunbookStep = { title: string; why: string; actions: string[]; commands?: string[]; verify: string[]; caution?: string };
type RunbookPhase = { number: string; title: string; outcome: string; steps: RunbookStep[] };

const runbook: RunbookPhase[] = [
  { number: "01", title: "Configure", outcome: "One exact repository and credential-free settings pass validation.", steps: [
    { title: "Prepare the workspace", why: "Install locked dependencies without changing the reviewed source state.", actions: ["Copy .env.example to .env when needed.", "Use Node.js 22+, npm 10, Python 3.13, uv, Docker Compose, and Xcode."], commands: ["npm ci", "uv sync --all-packages --locked"], verify: ["Lockfiles are unchanged.", "The Mathews worktree is clean."] },
    { title: "Bind the target repository", why: "Every task, token, preflight, webhook, and host operation must agree on one canonical repository.", actions: ["Set the absolute target repository root.", "Set the canonical owner/repository name and exact GitHub App, installation, and repository IDs.", "Configure the artifact root, database, Hermes endpoint, socket, and journal paths."], commands: ["uv run --package mathews-control-plane mathews-config-check"], verify: ["The configuration report exits successfully.", "No credential value appears in output."], caution: "A missing or broader repository binding blocks mutation." },
    { title: "Verify Keychain references", why: "Secrets stay on the Mac and never enter environment files, prompts, logs, or command arguments.", actions: ["Create generic-password items whose service/account match each keychain:// reference.", "Verify host HMAC, Hermes, GitHub App, webhook, Git transport, and test-account references individually."], commands: ["uv run --package mathews-host-agent mathews-keychain-check keychain://<service>/<account>"], verify: ["Each check reports presence only.", "No secret value is copied into a report or terminal command."] },
  ]},
  { number: "02", title: "Bootstrap authority", outcome: "The immutable MVP policy, prompts, and narrow review rule exist with deterministic fingerprints.", steps: [
    { title: "Apply migrations", why: "Authority records depend on the current durable schema.", actions: ["Start PostgreSQL first.", "Apply the repeatable migration chain once."], commands: ["docker compose -f infra/compose.yaml up -d --wait postgres", "npm run db:migrate"], verify: ["PostgreSQL is healthy.", "Migrations complete without concurrent writers."] },
    { title: "Preview the authority definition", why: "Dry-run exposes deterministic non-secret IDs and fingerprints without writing the database.", actions: ["Confirm the canonical acceptance repository before previewing.", "Review policy, prompt, rule, membership, actor, and approval-time fingerprints."], commands: ["uv run --package mathews-control-plane mathews-bootstrap-mvp-authority --dry-run"], verify: ["The definition names the intended repository.", "No prompt body, credential, database URL, or Keychain reference is printed."] },
    { title: "Create and inspect authority", why: "Exact replay is safe; any changed definition must fail closed.", actions: ["Run the bootstrap once.", "Inspect the stored records read-only.", "Record IDs and fingerprints for Phase 0 of the release gate."], commands: ["uv run --package mathews-control-plane mathews-bootstrap-mvp-authority", "uv run --package mathews-control-plane mathews-bootstrap-mvp-authority --inspect"], verify: ["First run reports created; exact replay reports replayed.", "Inspection matches the previewed definition."], caution: "Bootstrap installs authority records, not automatic production review-classifier wiring." },
  ]},
  { number: "03", title: "Install the host", outcome: "A private launchd-owned socket can execute only named, allowlisted operations.", steps: [
    { title: "Prepare host runtime", why: "The host owns Xcode, Simulator, Git workspaces, process groups, and the durable operation journal.", actions: ["Create the per-user runtime directory with mode 0700.", "Configure the exact repository root, operation allowlist, socket, journal, and host-auth reference.", "Keep credentials out of the plist."], verify: ["Runtime permissions are private.", "Repository preflight rejects unsafe remotes, paths, filters, and configuration."] },
    { title: "Install and verify LaunchAgent", why: "Production-style local operation requires launchd to own the socket and preserve the journal across restarts.", actions: ["Render and install the documented LaunchAgent.", "Confirm launchd owns the listening socket.", "Run the side-effect-free process probe and authenticated host health check."], verify: ["Only one host agent is active.", "The control plane and host resolve the same HMAC reference.", "Journal state survives restart."], caution: "Do not run the self-binding development host alongside the launchd-owned host." },
    { title: "Preflight the simulator harness", why: "Acceptance must start from a clean device and a pinned, repository-owned XCTest journey.", actions: ["Confirm runtime and device availability.", "Verify scheme, fixture, account recipe, source closure, and digests.", "Require shutdown, erase, boot, install, and pinned XCTest for each run."], verify: ["Preflight resolves the frozen base SHA.", "Harness and fixture paths are prohibited task-change paths."] },
  ]},
  { number: "04", title: "Start services", outcome: "API, worker, web, PostgreSQL, and launchd host are healthy with local authentication active.", steps: [
    { title: "Start the gate stack", why: "The gate keeps each long-running component explicit and avoids a second host agent.", actions: ["Start API, worker, and web in separate terminals.", "Keep PostgreSQL and the launchd host running."], commands: ["npm run dev:api", "npm run dev:worker", "npm run dev:web"], verify: ["API health passes at 127.0.0.1:8000.", "Web health passes at localhost:3000.", "Worker owns current durable leases."], caution: "For the release gate, do not use npm run dev; it also starts a conflicting development host agent." },
    { title: "Bootstrap or sign in the operator", why: "Local HTTP mutation is protected by a real account, exact origin, CSRF, secure cookies, and recent reauthentication.", actions: ["Issue a one-time bootstrap token only when no account exists.", "Use the token once at http://localhost:3000.", "Use localhost consistently for browser-facing URLs."], commands: ["npm run auth:bootstrap-token"], verify: ["The raw token is not retained.", "Authenticated cockpit and approval inbox load.", "Sensitive actions require recent password verification."] },
  ]},
  { number: "05", title: "Run acceptance", outcome: "One real task reaches explicit human handoff with its complete evidence chain intact.", steps: [
    { title: "Freeze and baseline", why: "The acceptance report must identify every mutable input before intake.", actions: ["Create the external mode-0700 report directory.", "Record run ID, roles, commits, repository/configuration/policy/harness versions, checks, and webhook ingress.", "Run the complete check, build, and PostgreSQL integration suite."], commands: ["npm run check", "npm run build", "npm run test:postgres"], verify: ["All required commands pass on the frozen SHA.", "The PostgreSQL suite executes rather than skipping."] },
    { title: "Execute the golden path", why: "A draft PR alone does not prove the MVP trust and recovery boundaries.", actions: ["Create and steer the bounded task, freeze the successor brief/contract, and record exactly one authorization.", "Observe implementation, exact-SHA validation, draft publication, preapproved repair, human one-off repair, readiness, and handoff.", "Complete the safety/recovery matrix and governed-learning promotion/rollback checks."], verify: ["Final state is HANDED_OFF.", "All exact-head dimensions agree.", "No merge, tag, signing, deployment, release, archive, or export occurred."] },
    { title: "Reconcile and decide", why: "GO is a strict evidence decision, not a qualitative confidence judgment.", actions: ["Compare the report to durable records and GitHub.", "Resolve or rerun every mismatch and defect.", "Record explicit GO or NO-GO and named sign-off."], verify: ["No required evidence is missing.", "Every live observation and named test passes.", "There are no unexplained deviations or unauthorized effects."], caution: "Any mismatch, required skip, secret exposure, duplicate effect, or unauthorized action is NO-GO." },
  ]},
  { number: "06", title: "Clean up & troubleshoot", outcome: "Temporary exposure is removed, durable evidence remains, and failures are diagnosed without weakening a gate.", steps: [
    { title: "Clean up the gate", why: "Temporary ingress and companion tasks must end without erasing the audit trail.", actions: ["Leave the generated PR unmerged in its observed draft state.", "Cancel disposable tasks through product paths.", "Restore dependencies and the prior webhook URL; stop ingress and revoke relay credentials.", "Retain journals, audit records, tombstones, and content-addressed evidence by policy."], verify: ["Temporary URL no longer forwards.", "Both worktrees have the expected clean state.", "No plaintext secret appears in repositories or report."] },
    { title: "Diagnose by boundary", why: "The safest fix starts with the component that owns the failed fact.", actions: ["Configuration failure: inspect redacted settings and repository binding.", "Host failure: inspect launchd health, socket ownership, journal, and preflight.", "Task stall: inspect state, approval, lease, checkpoint, and blocker in the cockpit.", "GitHub stall: inspect signed delivery, exact correlation, PR head, required checks, and review threads.", "Validation failure: compare contract/configuration/commit/tree and direct assertion evidence."], verify: ["The diagnosis identifies a durable fact or missing prerequisite.", "No row, token permission, branch rule, threshold, or validation requirement was weakened."] },
    { title: "Choose the correct recovery", why: "Retry is safe only when the effect is absent or idempotently observable.", actions: ["Use supported RETRY after restoring an unavailable dependency.", "Reconcile ambiguous effects instead of reissuing them.", "Create a new task for terminal FAILED or CANCELLED work.", "Rerun the complete golden path when exact-head or evidence continuity was invalidated."], verify: ["A new generation starts from a durable checkpoint.", "Old leases and results remain fenced.", "No duplicate external effect exists."] },
  ]},
];

export default function OperatorRunbookPage() {
  const [phaseIndex, setPhaseIndex] = useState(0);
  const [stepIndex, setStepIndex] = useState(0);
  const phase = runbook[phaseIndex];
  const step = phase.steps[stepIndex];
  function choosePhase(index: number) { setPhaseIndex(index); setStepIndex(0); }
  return <main className="doc-shell runbook-shell"><DocNav current="runbook" />
    <section className="doc-intro runbook-intro"><div><span className="section-number">07 / OPERATOR RUNBOOK</span><h1>Operate the loop.<br /><em>Protect the boundary.</em></h1></div><p>A practical path from a fresh checkout to a recorded acceptance decision. Select a phase and step for exact actions, checks, and stop conditions.</p></section>
    <section className="runbook-board" aria-label="Interactive operator runbook">
      <div className="runbook-phases" role="group" aria-label="Runbook phases">{runbook.map((item, index) => <button key={item.number} className={phaseIndex === index ? "selected" : ""} onClick={() => choosePhase(index)} aria-pressed={phaseIndex === index}><span>{item.number}</span><strong>{item.title}</strong></button>)}</div>
      <div className="runbook-phase-head"><span>PHASE {phase.number}</span><h2>{phase.title}</h2><p>{phase.outcome}</p></div>
      <div className="runbook-content"><div className="runbook-step-list" role="group" aria-label={`${phase.title} steps`}>{phase.steps.map((item, index) => <button key={item.title} className={stepIndex === index ? "selected" : ""} onClick={() => setStepIndex(index)} aria-pressed={stepIndex === index}><span>{String(index + 1).padStart(2,"0")}</span><strong>{item.title}</strong></button>)}</div>
      <article className="runbook-step-detail"><div className="runbook-step-title"><span>STEP {String(stepIndex + 1).padStart(2,"0")}</span><h3>{step.title}</h3><p>{step.why}</p></div><div className="runbook-columns"><div><span>ACTIONS</span><ol>{step.actions.map((item) => <li key={item}>{item}</li>)}</ol></div><div><span>VERIFY</span><ul>{step.verify.map((item) => <li key={item}>{item}</li>)}</ul></div></div>{step.commands && <div className="command-stack"><span>COMMANDS</span>{step.commands.map((command) => <code key={command}>{command}</code>)}</div>}{step.caution && <div className="runbook-caution"><span>STOP / CAUTION</span><p>{step.caution}</p></div>}</article></div>
    </section>
    <section className="diagnostic-map"><div className="section-heading"><span>QUICK DIAGNOSTIC MAP</span><h2>Start where truth is owned.</h2></div><div className="diagnostic-grid"><article><span>CONFIG</span><h3>Settings check fails</h3><p>Repository identity, required IDs, opaque references, absolute paths, and environment shape.</p></article><article><span>HOST</span><h3>Preflight or operation fails</h3><p>LaunchAgent, socket owner, HMAC reference, allowlist, journal, workspace, simulator, and Git isolation.</p></article><article><span>WORKFLOW</span><h3>Task stops advancing</h3><p>Current state, blocker, approval, lease, job generation, checkpoint, retry budget, and cancellation fence.</p></article><article><span>GITHUB</span><h3>PR status is stale</h3><p>Webhook signature, delivery receipt, repository/PR/head correlation, required checks, and open threads.</p></article></div></section>
    <footer className="site-footer"><span>MATHEWS / OPERATOR RUNBOOK</span><span>Configure → bootstrap → operate → prove</span></footer>
  </main>;
}
